# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: demo
  ports:
    - name: http
      protocol: TCP
      port: 801
      targetPort: 30405
      nodePort: 30405
    - name: https
      protocol: TCP
      port: 443 
      targetPort: 9377
  type: LoadBalancer